In [40]:
#creating numpy array using list
mylist=[1,2,3,4]
import numpy as np
a = np.array(mylist)
a

array([1, 2, 3, 4])

In [38]:
multiarr = [[1,2,3,4],
            [5,6,7,8]
]
b = np.array(multiarr)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
type(a)   #to print type of array

numpy.ndarray

In [30]:
a.ndim    #to print dimensions of array

1

In [32]:
a.shape  #to print shape of array 

(4,)

In [33]:
a.size   #to print size of array  

4

In [34]:
a.dtype  #to print type of elements of array

dtype('int32')

In [44]:
#creating numpy array using tuple
mytuple = (7,4,6,3,6)
t = np.array(mytuple)
t

array([7, 4, 6, 3, 6])

In [36]:
type(a)

numpy.ndarray

In [42]:
type(mylist)

list

In [45]:
type(mytuple)

tuple

In [47]:
np.zeros((3,4))  #to create a matrix with all elements as '0'

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
np.ones((2,2))  #to create a matrix with all elements as '1'

array([[1., 1.],
       [1., 1.]])

In [49]:
b.reshape(4,2)   #to reshape an array

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
b.flatten()   #to flatten an array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
#to append data horizontally
m = np.array((1,2,3,4))
n = np.array((1,2,3))
np.hstack((m,n))

array([1, 2, 3, 4, 1, 2, 3])

In [55]:
#to append data vertically
p = np.array((1,2,3,4))
q = np.array((1,2,3,5))
np.vstack((p,q))

array([[1, 2, 3, 4],
       [1, 2, 3, 5]])

In [59]:
#use of asarray()
np.asarray(b)[1] = 2     #to convert matrix(which is immutable) into array to make changes in it
b

array([[1, 2, 3, 4],
       [2, 2, 2, 2]])

In [62]:
#to create evenly spaced values
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])